#!/usr/bin/env bash

sxhkd &
unclutter &
# pgrep -x sxhkd > /dev/null || sxhkd &

# feh --bg-fill ~/bspwm/FusionA1.png &
# xsetroot -cursor_name left_ptr
# xrdb -merge $HOME/.Xresources &
xset r rate 200 50
~/.screenlayout/myLayout.sh

bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor HDMI-1 -d 1 2 3 4 5

bspc config border_width        0
bspc config window_gap          0
bspc config split_ratio       0.5

bspc config single_monocle      false
# bspc config focus_follows_pointer true
bspc config borderless_monocle    true
bspc config gapless_monocle     true

bspc config focused_border_color  "#BD93F9"
bspc config normal_border_color   "#282A36"
bspc config active_border_color   "#8BE9FD"
bspc config presel_feedback_color "#50FA7B"

bspc rule -a Emacs state=tiled
bspc rule -a zatharu state=tiled
